### ISSUE TITLE
Database Code Layer

### ISSUE THREAD

**Issue by thecodewizard** [Poomse8/Ever-Afters#3]
Make a database code layer, representative to the CRUD.
This database layer can be hardcoded, can be in a file system, can be in a database engine

Implement the DataRequesterHandler for the functions.
This handler is based that a TAG can only have ONE video, but a video can be used for multiple tags.

For hardcoded OR softcoded databases, one should be able to:
1. Request video path from Tag.
     -> This includes the base video path, the onscreen ending path and the offscreen ending path
     -> Base yourself on the object made (in issue #5)
2. Check if video path already exists (and if yes, if it's bound to any tag.)
     -> Finish the static methods in the video object
3. Check if tag identifier already exists (and if yes, if it's bound to any video.)
     -> Finish the static methods in the tag object

For softcoded databases only, foresee the following functions:
1. Register new Tag. (this tag identifier will be based on the pack and the image number. eg. BASIC-01, MATH-02)
2. Register new video (StartOnScreen bool/basepath/onscreen ending path/offscreen ending pat)
3. Bind Video object (in issue #5) to Tag.

These should also have the appropriate update and delete functions. (to update/delete the binding itself, or the video path or the tag identifier)

This code has to be called in order to let the engine know that you're the database he's looking for.
The database must implement the DataRequestHandler interface
//Register the database in the engine.
Engine.NewInstance().Database = this;

**Comment by thecodewizard** [comment]
The video object and the tag object can be found in the common layer.

**Comment by Hanh-Pham** [comment]
Functionaliteit is done
